import { ProviderProfile, Review, Booking, User, Wallet, Conversation } from "./types";

// ─── Mock Users ──────────────────────────────────────────────────────────────

export const MOCK_USER: User = {
  id: "usr_001",
  name: "Aryan Kapoor",
  email: "aryan@plusone.app",
  phone: "+91 98765 43210",
  avatar: "",
  isProvider: false,
  isVerified: true,
  verificationLevel: "phone",
  createdAt: new Date("2024-01-15"),
  trustScore: 82,
  city: "Mumbai",
  bio: "Always down for a good movie or coffee",
};

export const MOCK_PROVIDERS: ProviderProfile[] = [
  {
    id: "prv_001",
    name: "Riya Sharma",
    email: "riya@plusone.app",
    phone: "+91 98765 43211",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=80",
    isProvider: true,
    isVerified: true,
    verificationLevel: "selfie",
    createdAt: new Date("2023-08-10"),
    trustScore: 96,
    city: "Mumbai",
    bio: "Film buff, coffee addict, and part-time traveler. I've been exploring Mumbai's hidden spots for 5 years. Let's make your plans happen!",
    hourlyRate: 600,
    responseRate: 98,
    responseTime: "< 30 min",
    cancellationRate: 1.2,
    completedActivities: 127,
    totalEarnings: 82400,
    repeatCustomers: 43,
    ratings: {
      overall: 4.98,
      communication: 4.95,
      punctuality: 5.0,
      friendliness: 5.0,
      wouldMeetAgain: 98,
      count: 127,
    },
    reviews: [
      {
        id: "rev_001",
        bookingId: "bkg_001",
        reviewerId: "usr_002",
        reviewerName: "Rahul M.",
        reviewerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80",
        rating: {
          overall: 5,
          communication: 5,
          punctuality: 5,
          friendliness: 5,
          wouldMeetAgain: 100,
          count: 1,
        },
        comment: "Riya was absolutely fantastic! We went to see Dune 2 and grabbed coffee after. She's well-read, funny, and super easy to hang out with. Felt like meeting an old friend. Already booked her again for the next movie!",
        createdAt: new Date("2024-09-15"),
        verified: true,
      },
      {
        id: "rev_002",
        bookingId: "bkg_002",
        reviewerId: "usr_003",
        reviewerName: "Priya K.",
        reviewerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80",
        rating: {
          overall: 5,
          communication: 5,
          punctuality: 5,
          friendliness: 4.5,
          wouldMeetAgain: 100,
          count: 1,
        },
        comment: "Needed someone to explore the Kala Ghoda art district with. Riya knew all the best spots and galleries. She even took photos of me at each location. 10/10 would recommend!",
        createdAt: new Date("2024-08-28"),
        verified: true,
      },
      {
        id: "rev_003",
        bookingId: "bkg_003",
        reviewerId: "usr_004",
        reviewerName: "Vikram S.",
        reviewerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80",
        rating: {
          overall: 5,
          communication: 5,
          punctuality: 5,
          friendliness: 5,
          wouldMeetAgain: 95,
          count: 1,
        },
        comment: "New to Mumbai and Riya showed me the real city — not just tourist spots. Bandra walks, local food spots, everything. She's a genuine person. Highly recommend for anyone visiting or new to the city!",
        createdAt: new Date("2024-08-05"),
        verified: true,
      },
    ],
    activities: ["Movies", "Coffee", "City Exploration", "Museums", "Photography"],
    languages: ["Hindi", "English", "Marathi"],
    availability: [
      { day: "Monday", startTime: "10:00", endTime: "22:00", available: true },
      { day: "Tuesday", startTime: "10:00", endTime: "22:00", available: true },
      { day: "Wednesday", startTime: "10:00", endTime: "22:00", available: true },
      { day: "Thursday", startTime: "10:00", endTime: "22:00", available: true },
      { day: "Friday", startTime: "14:00", endTime: "23:00", available: true },
      { day: "Saturday", startTime: "10:00", endTime: "23:00", available: true },
      { day: "Sunday", startTime: "10:00", endTime: "20:00", available: true },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&q=80",
      "https://images.unsplash.com/photo-1449034446853-66c86144b0ad?w=400&q=80",
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&q=80",
    ],
    badges: [
      { id: "top_earner", label: "Top Earner", icon: "🏆", description: "Earned the most this month" },
      { id: "fast_responder", label: "Fast Responder", icon: "⚡", description: "Usually replies in under 30 minutes" },
      { id: "super_host", label: "Super Host", icon: "⭐", description: "Exceptional ratings from guests" },
    ],
    trustLevel: "Diamond",
    featured: true,
    lastActive: new Date("2024-09-20T14:30:00"),
  },
  {
    id: "prv_002",
    name: "Karthik Venkat",
    email: "karthik@plusone.app",
    phone: "+91 98765 43212",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    isProvider: true,
    isVerified: true,
    verificationLevel: "id",
    createdAt: new Date("2023-11-20"),
    trustScore: 88,
    city: "Bangalore",
    bio: "Tech professional by day, adventure seeker by weekend. Cricket, gaming, and food tours are my jam.",
    hourlyRate: 450,
    responseRate: 95,
    responseTime: "< 1 hr",
    cancellationRate: 3.5,
    completedActivities: 89,
    totalEarnings: 48700,
    repeatCustomers: 28,
    ratings: {
      overall: 4.87,
      communication: 4.8,
      punctuality: 4.9,
      friendliness: 4.9,
      wouldMeetAgain: 94,
      count: 89,
    },
    reviews: [
      {
        id: "rev_004",
        bookingId: "bkg_004",
        reviewerId: "usr_005",
        reviewerName: "Ananya P.",
        reviewerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80",
        rating: {
          overall: 5,
          communication: 5,
          punctuality: 5,
          friendliness: 5,
          wouldMeetAgain: 100,
          count: 1,
        },
        comment: "Karthik is the real deal. Played cricket with him on a Sunday morning and we ended up grabbing breakfast after. Great energy, very genuine person.",
        createdAt: new Date("2024-09-10"),
        verified: true,
      },
    ],
    activities: ["Sports", "Gaming", "Coffee", "City Exploration", "Food Tours"],
    languages: ["English", "Kannada", "Tamil"],
    availability: [
      { day: "Monday", startTime: "16:00", endTime: "22:00", available: true },
      { day: "Tuesday", startTime: "16:00", endTime: "22:00", available: true },
      { day: "Wednesday", startTime: "16:00", endTime: "22:00", available: true },
      { day: "Thursday", startTime: "16:00", endTime: "22:00", available: true },
      { day: "Friday", startTime: "14:00", endTime: "23:00", available: true },
      { day: "Saturday", startTime: "08:00", endTime: "23:00", available: true },
      { day: "Sunday", startTime: "08:00", endTime: "20:00", available: true },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=400&q=80",
    ],
    badges: [
      { id: "new", label: "New Host", icon: "🌱", description: "Started hosting this year" },
    ],
    trustLevel: "Gold",
    featured: false,
    lastActive: new Date("2024-09-20T12:00:00"),
  },
  {
    id: "prv_003",
    name: "Zara Ahmed",
    email: "zara@plusone.app",
    phone: "+91 98765 43213",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80",
    isProvider: true,
    isVerified: true,
    verificationLevel: "selfie",
    createdAt: new Date("2023-06-15"),
    trustScore: 94,
    city: "Delhi NCR",
    bio: "History nerd, foodie, and museum enthusiast. I'll show you Delhi you never knew existed. PhD student by day, explorer by weekend.",
    hourlyRate: 700,
    responseRate: 100,
    responseTime: "< 15 min",
    cancellationRate: 0.5,
    completedActivities: 203,
    totalEarnings: 142000,
    repeatCustomers: 76,
    ratings: {
      overall: 4.99,
      communication: 5.0,
      punctuality: 4.95,
      friendliness: 5.0,
      wouldMeetAgain: 99,
      count: 203,
    },
    reviews: [
      {
        id: "rev_005",
        bookingId: "bkg_005",
        reviewerId: "usr_006",
        reviewerName: "Neha G.",
        reviewerAvatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=100&q=80",
        rating: {
          overall: 5,
          communication: 5,
          punctuality: 5,
          friendliness: 5,
          wouldMeetAgain: 100,
          count: 1,
        },
        comment: "Zara is a walking encyclopedia of Delhi! She took me to 5 monuments in one day and shared stories I'd never heard. Also found us the best chai spot in Connaught Place. Unforgettable day.",
        createdAt: new Date("2024-09-18"),
        verified: true,
      },
    ],
    activities: ["Museums", "City Exploration", "Historical Tours", "Food Tours", "Coffee"],
    languages: ["Hindi", "English", "Urdu"],
    availability: [
      { day: "Monday", startTime: "09:00", endTime: "21:00", available: true },
      { day: "Tuesday", startTime: "09:00", endTime: "21:00", available: true },
      { day: "Wednesday", startTime: "09:00", endTime: "21:00", available: true },
      { day: "Thursday", startTime: "09:00", endTime: "21:00", available: true },
      { day: "Friday", startTime: "09:00", endTime: "22:00", available: true },
      { day: "Saturday", startTime: "09:00", endTime: "22:00", available: true },
      { day: "Sunday", startTime: "10:00", endTime: "18:00", available: true },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=400&q=80",
      "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=400&q=80",
    ],
    badges: [
      { id: "top_rated", label: "Top Rated", icon: "⭐", description: "4.99+ average rating" },
      { id: "super_host", label: "Super Host", icon: "⭐", description: "Exceptional ratings from guests" },
      { id: "fast_responder", label: "Fast Responder", icon: "⚡", description: "Usually replies in under 15 minutes" },
    ],
    trustLevel: "Diamond",
    featured: true,
    lastActive: new Date("2024-09-20T16:45:00"),
  },
  {
    id: "prv_004",
    name: "Arjun Mehta",
    email: "arjun@plusone.app",
    phone: "+91 98765 43214",
    avatar: "https://images.unsplash.com/photo-1599566150163-29194dcabd36?w=400&q=80",
    isProvider: true,
    isVerified: true,
    verificationLevel: "id",
    createdAt: new Date("2024-01-05"),
    trustScore: 78,
    city: "Pune",
    bio: "Fitness trainer, photography hobbyist, and coffee connoisseur. Let's get moving!",
    hourlyRate: 500,
    responseRate: 91,
    responseTime: "< 2 hr",
    cancellationRate: 5.2,
    completedActivities: 44,
    totalEarnings: 22100,
    repeatCustomers: 12,
    ratings: {
      overall: 4.72,
      communication: 4.6,
      punctuality: 4.7,
      friendliness: 4.9,
      wouldMeetAgain: 88,
      count: 44,
    },
    reviews: [
      {
        id: "rev_006",
        bookingId: "bkg_006",
        reviewerId: "usr_007",
        reviewerName: "Sneha R.",
        reviewerAvatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&q=80",
        rating: {
          overall: 5,
          communication: 5,
          punctuality: 5,
          friendliness: 5,
          wouldMeetAgain: 100,
          count: 1,
        },
        comment: "Great workout partner! Arjun planned a full circuit at the gym and then we went for a healthy breakfast. Really motivating.",
        createdAt: new Date("2024-09-01"),
        verified: true,
      },
    ],
    activities: ["Gym", "Sports", "Photography", "Coffee"],
    languages: ["Hindi", "English", "Marathi"],
    availability: [
      { day: "Monday", startTime: "06:00", endTime: "10:00", available: true },
      { day: "Tuesday", startTime: "06:00", endTime: "10:00", available: true },
      { day: "Wednesday", startTime: "06:00", endTime: "10:00", available: true },
      { day: "Thursday", startTime: "06:00", endTime: "10:00", available: true },
      { day: "Friday", startTime: "06:00", endTime: "10:00", available: true },
      { day: "Saturday", startTime: "07:00", endTime: "20:00", available: true },
      { day: "Sunday", startTime: "07:00", endTime: "18:00", available: true },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80",
    ],
    badges: [],
    trustLevel: "Silver",
    featured: false,
    lastActive: new Date("2024-09-19T18:00:00"),
  },
  {
    id: "prv_005",
    name: "Meera Iyer",
    email: "meera@plusone.app",
    phone: "+91 98765 43215",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&q=80",
    isProvider: true,
    isVerified: true,
    verificationLevel: "selfie",
    createdAt: new Date("2023-09-28"),
    trustScore: 91,
    city: "Goa",
    bio: "Born and raised in Goa. I know every beach, every cafe, and every hidden spot. Come explore with me! Also a certified scuba dive buddy.",
    hourlyRate: 800,
    responseRate: 97,
    responseTime: "< 45 min",
    cancellationRate: 2.1,
    completedActivities: 156,
    totalEarnings: 125000,
    repeatCustomers: 58,
    ratings: {
      overall: 4.95,
      communication: 4.9,
      punctuality: 4.95,
      friendliness: 5.0,
      wouldMeetAgain: 97,
      count: 156,
    },
    reviews: [
      {
        id: "rev_007",
        bookingId: "bkg_007",
        reviewerId: "usr_008",
        reviewerName: "Rohan D.",
        reviewerAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&q=80",
        rating: {
          overall: 5,
          communication: 5,
          punctuality: 5,
          friendliness: 5,
          wouldMeetAgain: 100,
          count: 1,
        },
        comment: "Meera showed me North Goa like a local! We skipped all the tourist traps and found the most amazing beach shacks and hidden waterfalls. She's genuinely the best guide you can get.",
        createdAt: new Date("2024-08-22"),
        verified: true,
      },
      {
        id: "rev_008",
        bookingId: "bkg_008",
        reviewerId: "usr_009",
        reviewerName: "Shweta P.",
        reviewerAvatar: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=100&q=80",
        rating: {
          overall: 5,
          communication: 5,
          punctuality: 5,
          friendliness: 5,
          wouldMeetAgain: 95,
          count: 1,
        },
        comment: "Came to Goa solo and was nervous. Meera made me feel completely comfortable from the start. We did a full day of beach hopping and dinner at a fantastic seafood place. Already planning my next trip back!",
        createdAt: new Date("2024-07-15"),
        verified: true,
      },
    ],
    activities: ["City Exploration", "Travel", "Beach Activities", "Photography", "Food Tours", "Festival Companion"],
    languages: ["Hindi", "English", "Konkani", "Portuguese"],
    availability: [
      { day: "Monday", startTime: "08:00", endTime: "21:00", available: true },
      { day: "Tuesday", startTime: "08:00", endTime: "21:00", available: true },
      { day: "Wednesday", startTime: "08:00", endTime: "21:00", available: true },
      { day: "Thursday", startTime: "08:00", endTime: "21:00", available: true },
      { day: "Friday", startTime: "08:00", endTime: "23:00", available: true },
      { day: "Saturday", startTime: "08:00", endTime: "23:00", available: true },
      { day: "Sunday", startTime: "08:00", endTime: "21:00", available: true },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=400&q=80",
      "https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=400&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80",
    ],
    badges: [
      { id: "top_earner", label: "Top Earner", icon: "🏆", description: "Earned the most this month" },
      { id: "super_host", label: "Super Host", icon: "⭐", description: "Exceptional ratings from guests" },
    ],
    trustLevel: "Gold",
    featured: true,
    lastActive: new Date("2024-09-20T11:20:00"),
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: "bkg_001",
    seekerId: "usr_002",
    providerId: "prv_001",
    activityId: "act_001",
    category: "Movies",
    title: "Dune 2 Screening",
    description: "Catch the latest blockbuster at Infinity Mall, Mumbai. Popcorn and discussion afterwards!",
    location: "Infinity Mall, Andheri, Mumbai",
    date: new Date("2024-09-21T15:00:00"),
    startTime: "15:00",
    endTime: "18:00",
    duration: 180,
    price: 1200,
    status: "completed",
    paymentStatus: "captured",
    reviewStatus: "completed",
    safetyChecked: true,
    emergencyContact: "+91 98765 43200",
    meetingPoint: "PVR Cinemas, Infinity Mall Lobby",
    createdAt: new Date("2024-09-15T10:00:00"),
    updatedAt: new Date("2024-09-21T18:30:00"),
  },
  {
    id: "bkg_002",
    seekerId: "usr_003",
    providerId: "prv_001",
    activityId: "act_002",
    category: "City Exploration",
    title: "Kala Ghoda Art Walk",
    description: "Explore Mumbai's art district — galleries, street art, and the best coffee spots.",
    location: "Kala Ghoda, Mumbai",
    date: new Date("2024-09-28T10:00:00"),
    startTime: "10:00",
    endTime: "13:00",
    duration: 180,
    price: 1800,
    status: "confirmed",
    paymentStatus: "hold",
    reviewStatus: "pending",
    safetyChecked: true,
    emergencyContact: "+91 98765 43201",
    meetingPoint: "RajabaiClock Tower, Kala Ghoda",
    createdAt: new Date("2024-09-20T14:00:00"),
    updatedAt: new Date("2024-09-20T14:00:00"),
  },
  {
    id: "bkg_003",
    seekerId: "usr_004",
    providerId: "prv_003",
    activityId: "act_003",
    category: "City Exploration",
    title: "Old Delhi Heritage Walk",
    description: "A guided walk through Chandni Chowk, Jama Masjid, and hidden gems of Old Delhi.",
    location: "Chandni Chowk, Delhi",
    date: new Date("2024-10-05T09:00:00"),
    startTime: "09:00",
    endTime: "13:00",
    duration: 240,
    price: 2800,
    status: "confirmed",
    paymentStatus: "hold",
    reviewStatus: "pending",
    safetyChecked: true,
    emergencyContact: "+91 98765 43202",
    meetingPoint: "Red Fort Metro Station, Exit 3",
    createdAt: new Date("2024-09-18T09:00:00"),
    updatedAt: new Date("2024-09-18T09:00:00"),
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    bookingId: "bkg_002",
    provider: MOCK_PROVIDERS[0],
    seeker: MOCK_USER,
    lastMessage: {
      id: "msg_001",
      bookingId: "bkg_002",
      senderId: "prv_001",
      content: "Hey! Looking forward to the art walk tomorrow. See you at 10 at the clock tower 👋",
      type: "text",
      createdAt: new Date("2024-09-20T16:00:00"),
      read: true,
    },
    unreadCount: 0,
    updatedAt: new Date("2024-09-20T16:00:00"),
  },
];

export const MOCK_WALLET: Wallet = {
  providerId: "prv_001",
  balance: 82400,
  pending: 1800,
  available: 80600,
  currency: "INR",
  transactions: [
    {
      id: "txn_001",
      type: "earn",
      amount: 600,
      description: "Activity: Dune 2 Screening",
      bookingId: "bkg_001",
      status: "completed",
      createdAt: new Date("2024-09-21T19:00:00"),
    },
    {
      id: "txn_002",
      type: "earn",
      amount: 1800,
      description: "Activity: Kala Ghoda Art Walk",
      bookingId: "bkg_002",
      status: "pending",
      createdAt: new Date("2024-09-20T14:00:00"),
    },
    {
      id: "txn_003",
      type: "payout",
      amount: -15000,
      description: "Bank Payout",
      status: "completed",
      createdAt: new Date("2024-09-01T10:00:00"),
    },
    {
      id: "txn_004",
      type: "bonus",
      amount: 500,
      description: "Referral Bonus — 5 referrals completed",
      status: "completed",
      createdAt: new Date("2024-08-15T12:00:00"),
    },
    {
      id: "txn_005",
      type: "earn",
      amount: 1200,
      description: "Activity: Bandra Photo Walk",
      bookingId: "bkg_old_001",
      status: "completed",
      createdAt: new Date("2024-08-10T16:00:00"),
    },
  ],
};

export const LEADERBOARD = {
  topRated: MOCK_PROVIDERS.sort((a, b) => b.ratings.overall - a.ratings.overall).slice(0, 5),
  topEarners: MOCK_PROVIDERS.sort((a, b) => b.totalEarnings - a.totalEarnings).slice(0, 5),
  mostBooked: MOCK_PROVIDERS.sort((a, b) => b.completedActivities - a.completedActivities).slice(0, 5),
};

// Re-export from constants
export { SAFETY_REMINDER } from "./constants";
