'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Compass, MapPin, Search, Sparkles } from 'lucide-react'

type Listing = { id: string; host_id: string; title: string; description: string; category: string; city: string; hourly_rate: number; currency: string; status: string }

export default function ExploreClient({ listings }: { listings: Listing[] }) {
  const [query, setQuery] = useState('')
  const [activeTab, setActiveTab] = useState<'offers' | 'plans'>('offers')
  const filtered = useMemo(() => listings.filter((item) => `${item.title} ${item.description} ${item.category} ${item.city}`.toLowerCase().includes(query.toLowerCase())), [listings, query])

  return <div className="app-container" style={{ maxWidth: 1000, margin: '0 auto', padding: '40px 24px' }}>
    <div style={{ marginBottom: 30 }}><p style={{ margin: '0 0 8px', color: 'var(--primary)', fontSize: 12, fontWeight: 700, letterSpacing: '.08em', textTransform: 'uppercase' }}>Find someone</p><h1 style={{ margin: 0, fontSize: 'clamp(32px, 6vw, 52px)', letterSpacing: '-.05em', lineHeight: .98 }}>Who are you<br />bringing along?</h1><p style={{ color: 'var(--muted-foreground)', margin: '14px 0 0', maxWidth: 540 }}>Browse real PlusOne offers or post your own plan. Because your group chat said “we’ll see” again.</p></div>
    <div className="app-card" style={{ padding: 18, marginBottom: 26 }}><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><Search size={19} style={{ color: 'var(--muted-foreground)', flexShrink: 0 }} /><input aria-label="What are you into?" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="What are you into? Try movies, coffee, Delhi..." style={{ border: 0, outline: 0, background: 'transparent', width: '100%', color: 'var(--foreground)', fontSize: 15 }} /></div><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 14 }}><button onClick={() => setActiveTab('offers')} className={`app-btn ${activeTab === 'offers' ? 'app-btn-primary' : 'app-btn-outline'}`}><Sparkles size={14} /> People with offers</button><Link href="/app/earn/marketplace" className="app-btn app-btn-outline" style={{ textDecoration: 'none' }}><ArrowRight size={14} /> People looking for a PlusOne</Link></div></div>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 16 }}><div><p style={{ margin: '0 0 5px', color: 'var(--primary)', fontSize: 11, fontWeight: 700, textTransform: 'uppercase' }}>Live in India</p><h2 style={{ margin: 0, fontSize: 24, fontWeight: 600 }}>People to meet.</h2></div><span style={{ color: 'var(--muted-foreground)', fontSize: 12 }}>{filtered.length} offers</span></div>
    {filtered.length === 0 ? <div className="app-card" style={{ padding: 28, color: 'var(--muted-foreground)' }}><Compass size={20} style={{ marginBottom: 10, color: 'var(--primary)' }} /><p style={{ margin: 0 }}>No one matches that search yet. Be the chaos — post a plan and let someone find you.</p></div> : <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: 16 }}>{filtered.map((item) => <Link key={item.id} href={`/listings/${item.id}`} style={{ textDecoration: 'none', color: 'inherit' }}><article className="app-card" style={{ height: '100%', padding: 20 }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, marginBottom: 14 }}><span className="app-badge app-badge-primary">{item.category}</span><strong style={{ fontSize: 13 }}>₹{Number(item.hourly_rate).toLocaleString('en-IN')}/hr</strong></div><h3 style={{ margin: '0 0 8px', fontSize: 18 }}>{item.title}</h3><p style={{ color: 'var(--muted-foreground)', fontSize: 13, lineHeight: 1.5, minHeight: 42 }}>{item.description}</p><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', color: 'var(--muted-foreground)', fontSize: 12, marginTop: 18 }}><span><MapPin size={13} style={{ verticalAlign: 'middle', marginRight: 4 }} />{item.city}, India</span><span style={{ color: 'var(--accent-foreground)', fontWeight: 600 }}>See the vibe →</span></div></article></Link>)}</div>}
  </div>
}
